name: Hapus Folder Bandel

on:
  push:
    branches:
      - main

jobs:
  delete-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_VPS2 }}

      - name: Add Server to Known Hosts
        run: ssh-keyscan -H 72.61.142.238 >> ~/.ssh/known_hosts

      - name: Hapus Folder Terkunci
        run: ssh root@72.61.142.238 "rm -rf /home/pbmagency.id/sub2_laravel"